---
- name: create ark dir
  file:
    path: "{{ playbook_dir }}/ark"
    state: directory

- name: get ark
  unarchive:
    src: https://github.com/heptio/velero/releases/download/v0.10.1/ark-v0.10.1-linux-amd64.tar.gz
    dest: "{{ playbook_dir }}/ark"
    remote_src: yes
